### ISSUE TITLE
Very well done on getting it deployed to Heroku 🥳

### ISSUE THREAD

**Issue by Moggach** [fac-23/nom-nom-app#24]
and adding the deployed link to the repo - nice work 👍

**Comment by duckRabbitPy** [comment]
+ Aesthetically pleasing, great design
+ Good use of flexbox and flex wrap
+ Number restrictions for the user input (we couldn't break it)
+ Good accessibility 
+ Functionality is great, we love the stars 
+ Very detailed and clear readMe

⭐️⭐️⭐️⭐️⭐️
