### ISSUE TITLE
Think you can move database folder out of src folder 

### ISSUE THREAD

**Issue by Moggach** [fac-23/nom-nom-app#26]
Think this would make file structure a bit simpler. Not sure if the src folder is doing anything here.

**Comment by oliverjam** [comment]
Yeah usually `src` (or `source`) contains all the actual "code"—since the root of the project gets so busy with e.g. `package.json`, `Procfile`, `.prettierrc` etc. These config files are mostly for computers not humans, so it's nice to have a subfolder with all the stuff you actually care about in.
